version: '3'
services:
  sentinel-dashboard:
    image: ypjalt/sentinel-dashboard
    container_name: sentinel-dashboard
    restart: always
    environment:
      JAVA_OPTS: "-Dserver.port=8080 -Dcsp.sentinel.dashboard.server=localhost:8080 -Dproject.name=sentinel-dashboard -Djava.security.egd=file:/dev/./urandom -Dcsp.sentinel.api.port=8719"
    ports: #避免出现端口映射错误，建议采用字符串格式 8080端口为Dockerfile中EXPOSE端口
      - "8080:8080"
      - "8719:8719"
    volumes:
      - ./sentinel/logs:/root/logs

# http://localhost:8080/#/login
# sentinel