version: '3'
services:
  mysql:
    restart: always
    image: mysql/mysql-server:latest
    container_name: my_mysql
    volumes:
      - ./mysql/mydir:/mydir
      - ./mysql/datadir:/var/lib/mysql
      - ./mysql/conf/my.cnf:/etc/my.cnf
      # 数据库还原目录 可将需要还原的sql文件放在这里
      - ./mysql/source:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
      - "TZ=Asia/Shanghai"
    ports:
      - 3306:3306

      
# 启动成功运行如下命令开启远程连接
# docker exec -it my_mysql /bin/bash
# mysql -uroot -p123456
# use mysql;
# alter user 'root'@'%' identified with mysql_native_password by '123456';
# flush privileges;
