version: "3"
services:
  mqnamesrv:
    image: dyrnq/rocketmq:latest
    container_name: mqnamesrv
    ports:
      - 9876:9876
    environment:
      JAVA_OPT: -server -Xms256m -Xmx256m
      MAX_POSSIBLE_HEAP: 1000000000
    command: sh mqnamesrv
  mqbroker:
    image: dyrnq/rocketmq:latest
    container_name: mqbroker
    ports:
      - 10911:10911
      - 10909:10909
    volumes:
      - ./rocketmq/conf/broker.conf:/opt/rocketmq/conf/broker.conf
    environment:
      JAVA_OPT_EXT: -server -Xms256m -Xmx256m -Xmn128m
      NAMESRV_ADDR: mqnamesrv:9876
    command: sh mqbroker -n mqnamesrv:9876 -c /opt/rocketmq/conf/broker.conf
  mqconsole:
    image: candice0630/rocketmq-console-ng:2.0
    container_name: mqconsole
    ports:
      - 19876:8080
    environment:
      JAVA_OPTS: -Drocketmq.namesrv.addr=mqnamesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=falses
    depends_on:
      - mqnamesrv